### PR TITLE
MSB_FIRST to MSBFIRST. Fails to compiles without change.

### PR DESCRIPTION
**Pull request by ChristianHaroldsen**
I could not get the example code MinimalistExample to compile without making this change first.

### CODE REVIEW

**Comment by BrentWilkins** [comment]
I love that your editor strips off trailing whitespace, but making variable names less readable cannot be the real fix. Is it written differently somewhere else in the code?

**Comment by BrentWilkins** [comment]
I love that your editor strips trailing whitespace! Here is how the code broke a few days ago:

> commit a440c1dce71415d03b3babd0c77441ffef160cdd
> Author: Elias Santistevan <elias.santistevan@sparkfun.com>
> Date:   Tue Nov 9 13:39:05 2021 -0700

**Comment by ChristianHaroldsen** [comment]
I think the issue is the SPI library uses the variable name MSBFIRST, not MSB_FIRST.
________________________________

**Comment by edspark** [comment]
Thank you for the pull request! However `MSB_FIRST` is used for all other platforms except the ESP32 and I completely forgot that little tidbit. I'll get a change pushed right away.

**Comment by edspark** [comment]
Thanks again @ChristianHaroldsen, fixed [here](https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library/commit/fa686db5006826a84e5d930bb83838406905b571)

**Comment by limjh16** [comment]
Hey! Sorry to revive this old PR, but `MSB_FIRST` fails to compile for an Arduino Nano as well, since it uses `MSBFIRST` instead. Are you able to change that as well?

**Pull request closed without merging**
